/* DO NOT EDIT. This file was automatically generated by mkopttab. */


OptInfo optTab[]= {
  OPT_ENTRY(
    /* longOpt */	"build-display",
    /* shortOpt */	'\0',
    /* argType */	NO_OPT_FLAG,
    /* id */		BUILD_DISPLAY_OPT,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		buildFn,
    /* doc */		"\
--build-display           Display parameters used to build zyacc and\n\
                          exit.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"debug",
    /* shortOpt */	't',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		DEBUG_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.cmdLineDebug,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--debug[=1|0] | -t[1|0]   Allow tracing of generated parser \n\
                          (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"defines",
    /* shortOpt */	'd',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		DEFINES_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doDefs,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--defines[=1|0] |         Output a .h definitions file \n\
  -d[1|0]                 (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"file-prefix",
    /* shortOpt */	'b',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		FILE_PREFIX_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.filePrefix,
    /* optFn */		stringOptFn,
    /* doc */		"\
--file-prefix PREFIX |    Specify prefix to be used for all output\n\
  -b PREFIX               files (default: `yy').\n\
\tyy\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"grammar",
    /* shortOpt */	'g',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		GRAMMAR_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doGram,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--grammar[=1|0] |         Output a reference grammar file to <stdout>\n\
  -g[1|0]                 and exit (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"help",
    /* shortOpt */	'h',
    /* argType */	NO_OPT_FLAG,
    /* id */		HELP_OPT,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		helpFn,
    /* doc */		"\
--help | -h               Print summary of options and exit.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"html",
    /* shortOpt */	'H',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		HTML_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doHTML,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--html[=1|0] | -H[1|0]    Write html parser description in .html file \n\
                          (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"lines",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		LINES_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doLine,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--lines[=1|0]             Output #line directives in generated parser\n\
                          file (default: `1').\n\
\t1\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"longer-rule-prefer",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		RR_LONGER_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doRRLonger,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--longer-rule-prefer[=1|0] When resolving a reduce-reduce conflict\n\
                          prefer the longer rule (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"output-file",
    /* shortOpt */	'o',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		OUTPUT_FILE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.outName,
    /* optFn */		stringOptFn,
    /* doc */		"\
--output-file outFile |   Specify the name outFile for the parser file.\n\
  -o outFile              \n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"name-prefix",
    /* shortOpt */	'p',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		NAME_PREFIX_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.extPrefix,
    /* optFn */		stringOptFn,
    /* doc */		"\
--name-prefix PREFIX |    Specify prefix to be used for all external\n\
  -p PREFIX               symbols (default: `yy').\n\
\tyy\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"term-suffix",
    /* shortOpt */	'\0',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		TERM_SUFFIX_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.termSuffix,
    /* optFn */		stringOptFn,
    /* doc */		"\
--term-suffix SUFFIX      Specify suffix string to be appended to all\n\
                          external terminal names (default).\n\
\t\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"verbose",
    /* shortOpt */	'v',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		VERBOSE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doVerbose,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--verbose[=1|0] |         Write verbose parser description in .output\n\
  -v[1|0]                 file (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"version",
    /* shortOpt */	'V',
    /* argType */	NO_OPT_FLAG,
    /* id */		VERSION_OPT,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		versionFn,
    /* doc */		"\
--version | -V            Print version number and exit.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"yacc",
    /* shortOpt */	'y',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		YACC_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doYacc,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--yacc[=1|0] | -y[1|0]    Name output files like YACC (default: `0').\n\
\t0\
"
  )
};
