/* DO NOT EDIT. This file was automatically generated by mkopttab. */


OptInfo optTab[]= {
  OPT_ENTRY(
    /* longOpt */	"16-bit",
    /* shortOpt */	'\0',
    /* argType */	NO_OPT_FLAG,
    /* id */		CHAR_SET_SIZE_16_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.charSetSize,
    /* optFn */		charSetSizeFn,
    /* doc */		"\
--16-bit                  Generate a unicode-ready scanner which\n\
                          handles 16-bit characters.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"7-bit",
    /* shortOpt */	'7',
    /* argType */	NO_OPT_FLAG,
    /* id */		CHAR_SET_SIZE_7_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.charSetSize,
    /* optFn */		charSetSizeFn,
    /* doc */		"\
--7-bit | -7              Generate a scanner which handles only 7-bit\n\
                          characters.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"8-bit",
    /* shortOpt */	'8',
    /* argType */	NO_OPT_FLAG,
    /* id */		CHAR_SET_SIZE_8_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.charSetSize,
    /* optFn */		charSetSizeFn,
    /* doc */		"\
--8-bit | -8              Generate a scanner which handles 8-bit\n\
                          characters (default).\n\
\t\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"align",
    /* shortOpt */	'a',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		ALIGN_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.align,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--align[=1|0] | -a[1|0]   Generate a scanner which does not use short\n\
                          integer tables (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"array",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		ARRAY_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doArray,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--array[=1|0]             Implement yytext as an array \n\
                          (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"backup-optimize",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		BACKUP_OPTIMIZE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.backupOptimize,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--backup-optimize[=1|0]   Optimize the scanner for patterns which\n\
                          require it to backup (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	NULL,
    /* shortOpt */	'c',
    /* argType */	NO_OPT_FLAG,
    /* id */		POSIX_COMPLIANCE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.dummy,
    /* optFn */		charOptFn1,
    /* doc */		"\
-c                        Deprecated option included for POSIX\n\
                          compliance.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"bin-code-param",
    /* shortOpt */	'\0',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		BIN_CODE_PARAM_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.binCodeParam,
    /* optFn */		intOptFn1,
    /* doc */		"\
--bin-code-param N        Binary search in code-scanner if # input\n\
                          ranges <= N (default: `16').\n\
\t16\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"code-scan",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		CODE_SCAN_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doCode,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--code-scan[=1|0]         Generated scanner encodes DFA in code\n\
                          instead of tables (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"compress",
    /* shortOpt */	'C',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		COMPRESS_OPT,
    /* checkP */		compressOpts,
    /* valP */		(VOIDP) &options.compress,
    /* optFn */		stringValOptFn,
    /* doc */		"\
--compress Type |         Use table compression of Type `no', \n\
  -C Type                 `comb' or `iterative' (default: `comb').\n\
\tcomb\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"col-waste-percent",
    /* shortOpt */	'\0',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		COL_WASTE_OPT,
    /* checkP */		colWasteOpts,
    /* valP */		(VOIDP) &options.colWastePercent,
    /* optFn */		intOptFn1,
    /* doc */		"\
--col-waste-percent PERCENT When --compress=none & --table=state, use\n\
                          a 2-dimensional table with the # of columns\n\
                          a power of 2 if the percentage of wasted\n\
                          columns is <= PERCENT (`0' <= PERCENT and \n\
                          PERCENT <= 100) (default: `50').\n\
\t50\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"debug",
    /* shortOpt */	'd',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		DEBUG_ON_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doDebug,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--debug[=1|0] | -d[1|0]   Turn on debugging in generated scanner \n\
                          (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"default-action",
    /* shortOpt */	's',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		DEFAULT_ACT_OPT,
    /* checkP */		defaultOpts,
    /* valP */		(VOIDP) &options.defaultAct,
    /* optFn */		stringValOptFn,
    /* doc */		"\
--default-action ACT |    Set default action for unmatched character\n\
  -s ACT                  to ACT `echo', `error', `fatal' or `ignore' \n\
                          (default: `echo').\n\
\techo\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"ecs",
    /* shortOpt */	'E',
    /* argType */	SYNONYM_OPT_FLAG,
    /* id */		0,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		NULL,
    /* doc */		NULL
  ),
  OPT_ENTRY(
    /* longOpt */	"equiv-classes",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		EQ_CLASSES_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.equivClasses,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--ecs[=1|0] | -E[1|0] |   Partition input characters into equivalence\n\
  --equiv-classes[=1|0]   classes (default: `1').\n\
\t1\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"help",
    /* shortOpt */	'h',
    /* argType */	NO_OPT_FLAG,
    /* id */		HELP_OPT,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		helpFn,
    /* doc */		"\
--help | -h               Print summary of options and exit.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"ignore-case",
    /* shortOpt */	'i',
    /* argType */	SYNONYM_OPT_FLAG,
    /* id */		0,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		NULL,
    /* doc */		NULL
  ),
  OPT_ENTRY(
    /* longOpt */	"caseless",
    /* shortOpt */	'\0',
    /* argType */	SYNONYM_OPT_FLAG,
    /* id */		0,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		NULL,
    /* doc */		NULL
  ),
  OPT_ENTRY(
    /* longOpt */	"case-insensitive",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		IGNORE_CASE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.ignoreCase,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--ignore-case[=1|0] |     Generate a case insensitive scanner \n\
  -i[1|0] |               (default: `0').\n\
  --caseless[=1|0] |      \n\
  --case-insensitive[=1|0] \n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"lex-compat",
    /* shortOpt */	'l',
    /* argType */	NO_OPT_FLAG,
    /* id */		LEX_COMPAT_OPT,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		lexCompatFn,
    /* doc */		"\
--lex-compat | -l         Lex compatibility (equivalent to --array\n\
                          --yylineno --reject).\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"lin-code-param",
    /* shortOpt */	'\0',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		LIN_CODE_PARAM_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.linCodeParam,
    /* optFn */		intOptFn1,
    /* doc */		"\
--lin-code-param N        Linear search in code-scanner if #\n\
                          successors <= N (default: `4').\n\
\t4\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"line-dir",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		LINE_DIR_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.lineDir,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--line-dir[=1|0]          Output #line directives to generated scanner \n\
                          (default: `1').\n\
\t1\
"
  ),
  OPT_ENTRY(
    /* longOpt */	NULL,
    /* shortOpt */	'n',
    /* argType */	NO_OPT_FLAG,
    /* id */		POSIX_COMPLIANCE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.dummy,
    /* optFn */		charOptFn1,
    /* doc */		"\
-n                        Deprecated option included for POSIX\n\
                          compliance.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"output",
    /* shortOpt */	'o',
    /* argType */	INTERN_OPT_FLAG|REQUIRED_OPT_FLAG,
    /* id */		OUTPUT_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.outFileName,
    /* optFn */		stringOptFn,
    /* doc */		"\
--output FILENAME |       Generate scanner in file FILENAME \n\
  -o FILENAME             (default: `lex.yy.c').\n\
\tlex.yy.c\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"prefix",
    /* shortOpt */	'P',
    /* argType */	INTERN_OPT_FLAG|REQUIRED_OPT_FLAG,
    /* id */		PREFIX_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.prefix,
    /* optFn */		stringOptFn,
    /* doc */		"\
--prefix PREFIX |         Use PREFIX as prefix of certain global\n\
  -P PREFIX               names in
generated scanner (default: `yy').\n\
\tyy\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"sentinel",
    /* shortOpt */	'S',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		SENTINEL_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.sentinelChar,
    /* optFn */		intOptFn0,
    /* doc */		"\
--sentinel CHAR-CODE |    Use character with decimal code CHAR-CODE\n\
  -S CHAR-CODE            as sentinel (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"reject",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		REJECT_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doReject,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--reject[=1|0]            Allow REJECT actions in generated scanner \n\
                          (default: `1').\n\
\t1\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"stdio",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		STDIO_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.doStdio,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--stdio[=1|0]             Use standard I/O for all scanner input \n\
                          (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"table",
    /* shortOpt */	'T',
    /* argType */	REQUIRED_OPT_FLAG,
    /* id */		TABLE_OPT,
    /* checkP */		tableOpts,
    /* valP */		(VOIDP) &options.tableEntry,
    /* optFn */		stringValOptFn,
    /* doc */		"\
--table Type | -T Type    Use table entries of Type `address', \n\
                          `difference' or `state' (default: `state').\n\
\tstate\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"to-stdout",
    /* shortOpt */	't',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		TO_STDOUT_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.toStdOut,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--to-stdout[=1|0] |       Write generated scanner to stdout \n\
  -t[1|0]                 (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"trace",
    /* shortOpt */	'T',
    /* argType */	INTERN_OPT_FLAG|OPTIONAL_OPT_FLAG,
    /* id */		TRACE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.traceFileName,
    /* optFn */		stringOptFn,
    /* doc */		"\
--trace[=TRACE_FILE] |    Run zlex in trace mode, generating\n\
  -T[TRACE_FILE]          extensive output in file TRACE_FILE which\n\
                          defaults to stdout.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"transition-compress",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		TRANSITION_COMPRESS_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.transitionCompress,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--transition-compress[=1|0] Compress transitions for non-switch\n\
                          states in code scanner (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"verbose",
    /* shortOpt */	'v',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		VERBOSE_OPT,
    /* checkP */		NULL,
    /* valP */		(VOIDP) &options.isVerbose,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--verbose[=1|0] |         Generate somewhat verbose statistics\n\
  -v[1|0]                 describing DFA (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"version",
    /* shortOpt */	'V',
    /* argType */	NO_OPT_FLAG,
    /* id */		VERSION_OPT,
    /* checkP */		NULL,
    /* valP */		NULL,
    /* optFn */		versionFn,
    /* doc */		"\
--version | -V            Print version number and exit.\n\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"whitespace",
    /* shortOpt */	'w',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		WHITESPACE_OPT,
    /* checkP */		NULL,
    /* valP */		&options.wsInPatterns,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--whitespace[=1|0] |      Allow whitespace within lex patterns \n\
  -w[1|0]                 (default: `0').\n\
\t0\
"
  ),
  OPT_ENTRY(
    /* longOpt */	"yylineno",
    /* shortOpt */	'\0',
    /* argType */	OPTIONAL_OPT_FLAG,
    /* id */		YYLINENO_OPT,
    /* checkP */		NULL,
    /* valP */		&options.doYYLineNo,
    /* optFn */		yesNoOptFn,
    /* doc */		"\
--yylineno[=1|0]          Maintain count of line number in global\n\
                          variable yylineno (default: `0').\n\
\t0\
"
  )
};
